### PR TITLE
added docs pages and changed index links

### PR DESCRIPTION
**Pull request by todrobbins**
Some of the text formatting may need adjustment for readability but this brings in three pages from the [`docs` folder](https://github.com/AgregoreWeb/agregore-browser/tree/master/docs):

Screen Recording 2021-02-02 at 4 52 00 PM

### CODE REVIEW

**Comment by RangerMauve** [comment]
This is looking great so far.

One comment though, I think the centered styling that was there initially isn't working too well with this new content. 😅

Maybe we should left-align it by default and only do centering on the main page or something?

Might also make sense to reduce the max width for the body a bit too.

**Comment by KyGost** [comment]
Re centering, one could do what we've done for markdown, have a padding on the sides to pull everything into the center while having left align for readability and such.

**Comment by todrobbins** [comment]
Fixed:

Screen Shot 2021-02-02 at 5 10 40 PM

Screen Shot 2021-02-02 at 5 11 23 PM

Screen Shot 2021-02-02 at 5 11 57 PM

**Review by RangerMauve — APPROVED** [review]
Woot! I love it, thank you. 😁 Feel free to merge

**Comment by RangerMauve** [comment]
Woot! 🎉🎉🎉

**Pull request merged**
